- name: app
  format: "$remote_addr - $remote_user [$time_local] \"$method $request $http_version\" $status $body_bytes_sent \"$http_referer\" \"$http_user_agent\" $upstream_response_time"
  source_files:
    - ./test/nginx.log
#  static_config:
#    foo: foo
  relabel_config: 
    source_labels: 
      - request
      - method
      - status
    replacement:
      request:
        trim: "?"
        replace:
          - target: /xhr/v2/sites/\d+$
            value: /xhr/v2/sites/:site_id
          - target: /xhr/v2/sites/\d+/scans/\d+
            value: /xhr/v2/sites/:site_id/scans/:scan_id
